### ISSUE TITLE
System added twice

### ISSUE THREAD

**Issue by Sroka** [Dreaming381/lsss-wip#1]
Hey, on fresh download on MacOs I get following error messages:
![obraz](https://user-images.githubusercontent.com/2983710/84588669-d5ad0680-ae29-11ea-9d98-7d5d655e9566.png)

**Comment by Dreaming381** [comment]
This is a Unity bug produced by the Entity Debugger and DOTS Editor (they both do it). It happens because I have manually added TransformSystemGroup to run at two different points in the frame. This is a completely legitimate thing to do, and the game runs fine. Unity is aware of the issue too.
https://forum.unity.com/threads/dots-editor-0-7-0-preview-release.898781/#post-5942249
